App\Entity\Image:
  properties:
    file:
      - Image:
          minWidth: 600
          minWidthMessage: "L'image doit faire 600 pixels de largeur minimum"
          maxWidth: 2500
          maxWidthMessage: "L'image doit faire 2500 pixels de hauteur maximum"
