App\Domain\Models\Media:
  properties:
    file:
      minWidth: 200
      minWidthMessage: "L'image doit avoir une largeur minimum de 200 pixel"
      maxWidth: 200
      maxWidthMessage: "L'image doit avoir une largeur maximum de 200 pixel"
      minHeight: 200
      minHeightMessage: "L'image doit avoir une hauteur maximum de 200 pixel"
      maxHeight: 200
      maxHeightMessage: "L'image doit avoir une hauteur maximum de 200 pixel"
      mimeTypes: image/png
      mimeTypesMessage: "Le format de fichier doit être du PNG."