App\Entity\Trick:
  constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: name
            errorPath: name
            message: "Le nom du Trick existe déja."

  properties:

      name:
        - NotBlank:
            message: "Le nom du Trick est obligatoire !"
        - Length:
            min: 3
            minMessage: "Le nom du Trick est trop court."
            max: 255
            maxMessage: "Le nom du Trick est trop long."

      defaultImage:
          - NotBlank:
              message: "L'image pricipale est obligatoire !"
          - Valid: ~

      description:
          - NotBlank:
              message: "La déscription ne peut pas être vide !"
          - Length:
              min: 10
              minMessage: "La déscription du Trick est trop courte."

      images:
          - Valid: ~

      videos:
          - Valid: ~

