parameters:
    locale: 'en'
    image_directory: '%kernel.project_dir%/public/uploads/images'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'


    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    App\Services\FileUploader:
        arguments:
            $targetDirectory: '%image_directory%'

    App\Services\FileRemover:
        arguments:
            $path: '%image_directory%'

    app.security.LoginForm:
        class: App\Security\LoginForm


